### ISSUE TITLE
Get CI working

### ISSUE THREAD

**Issue by shawnlaffan** [PDLPorters/Alien-Proj4#5]
The travis and appveyor control files are in place, but the services need to be enabled.

**Comment by shawnlaffan** [comment]
Travis can be enabled from the travis-ci.org end of the system, but I cannot sync the repo.  This is presumably because I am not the owner.

Appveyor might be the same.

**Comment by mohawk2** [comment]
As far as I know, anyone who has permissions can link "their" AppVeyor account to the repo. If you can't, I ought to be able to.

Travis is a bit more mysterious, since I'm an "owner" of it. The UI now is that one goes to http://travis-ci.org/PDLPorters, select the repo, and then "enable", but it's telling me I don't have permissions.

**Comment by shawnlaffan** [comment]
Appveyor is up and running.  

Maybe travis needs someone else from PDLPorters?

**Comment by shawnlaffan** [comment]
https://ci.appveyor.com/project/shawnlaffan/alien-proj4

**Comment by mohawk2** [comment]
Nice work on AppVeyor!

**Comment by shawnlaffan** [comment]
Looks like a false dawn for appveyor.  It is not triggering for the branch and PR I just submitted.

A manual start is rerunning the previous build.

**Comment by mohawk2** [comment]
I've just successfully added A::P4 to my AppVeyor "projects", and now it works, and even passes. Travis is also activated. Closing.

**Comment by mohawk2** [comment]
I also updated the POD and the README.md so GH now shows right badges, and next CPAN release will too.

By the way, the latest release is showing that FreeBSD (only, though previous versions also failed on one Linux) is mostly passing except for the one odd situation we've already seen, and it says the symlinks etc are as expected, but the dynamic linker can't find the thing. We could make the test also `diag` the `LD_LIBRARY_PATH`, I suppose.

I think that without more information, we won't get any closer to fixing it. Also, given the very high pass rate, we should probably focus our efforts on eg making PROJ5 / 6 work instead? :-)

**Comment by shawnlaffan** [comment]
Good to hear appveyor works and the badges are up to date.  

I agree to let the fails be for now.  I suspect it is an issue beyond Alien::Proj4, perhaps in Inline or Alien::Base, or perhaps something in that tester's system.

WRT Proj5/6, Alien::proj already does that.  We have PDLA::GIS and PDLA::Transform working with Proj4, and the Alien setup means it will be isolated from system proj5/6 installations so they can be left alone now.  

If one were to go for purity then the ```load_projection_descriptions``` code could also be shifted into PDLA::Transform, as I think that's the only code that uses it.  I'm not sure it's needed, though.
